### ISSUE TITLE
almost - screen capture res

### ISSUE THREAD

**Issue by terrorfirma** [explorers-nation/SeppOcrClient#1]
well.. the sizing for the screen seems to work good for the width. I can capture the top most two factions shown, but the bottom two are not in the capture area even if I distort the vertical numbers and the percent change thing does not seem to do anything.

![capture](https://user-images.githubusercontent.com/19792731/33732303-ee21cf1c-db3a-11e7-9951-ba69f1edcfd8.JPG)

**Comment by gregmalcolm** [comment]
Failed to replace a variable in one place, oops!

Fixed in 1.6.3
